---
title: "webapi"
author: "Coskun Erden"
date: "4/9/2022"
output:
  word_document: default
  html_document: default
---


```{r}

library(httr)
library(rvest)
library(xml2)
library(xml2)
library(tibble)
```

We want to get the news headlines or breaking news of a particular country. We can show all the unfiltered news or we can search for any news of the category business, entertainment, sports, technology etc. We can extract news of a given date and time.

Note: country and source cannot be put together in the search parameter.


```{r}
url <- "https://newsapi.org/v2/"
req_data <- httr::GET(
  paste0(url, "top-headlines?country =us&category=sports&apiKey=f8acc8a2a90845d5b57ab446ba1d9827")
)
tr_news <- httr::content(req_data, as = "parsed")
str(tr_news)
```
```{r}

url <- "https://newsapi.org/v2/"
req_data <- httr::GET(
  paste0(url, "top-headlines?country=us&apiKey=f8acc8a2a90845d5b57ab446ba1d9827")
)
tr_news <- httr::content(req_data, as = "parsed")
str(tr_news)

```



```{r}
news_df <- function(x, verbose=FALSE) {
  if (verbose) {
    cat(x$name)
    cat("\n")
  }
  title <- character()
  description <- character()
  content <- character()
  imageURL <- character()
  published_date <-character()
  
  
  
  #tr_news[3] is the news article
    for(i in 1:3){
    title=c(title, x$articles[[i]]$title)
    description=c(description,x$articles[[i]]$description)
    published_date=x$articles[[i]]$publishedAt
    print(published_date)
}
  
  tibble (
    title = title,
    description = description,
    published_date=published_date
  )
}
```

```{r}
tr <- news_df(tr_news)
tr
```

